### ISSUE TITLE
More code is underlined in the error report than what actually contains error

### ISSUE THREAD

**Issue by jhrcek** [jfmengels/review-unused#13]
See the following example

![Screenshot from 2020-04-20 10-23-06](https://user-images.githubusercontent.com/2716069/79730431-218f7380-82f1-11ea-816d-cfd7e20b1dd7.png)

**Comment by jfmengels** [comment]
Thanks for reporting this :)

I moved this issue to `jfmengels/review-unused` because I thought that the issue lied here. With your last comment I notice that that might not be true, but it's still most likely.

I don't mind that the `, ` is included, though it doesn't bring much information, so let's remove it. But I am confused as to why we get different treatments like in your last comment.

Could you provide an SSCCE for this?

**Comment by jhrcek** [comment]
I managed to get it down to this: https://github.com/jhrcek/elm-review-sscce

To reproduce, I just run elm-review (installed globally as npm package) in the project root and I get this:
![Screenshot from 2020-04-20 13-30-36](https://user-images.githubusercontent.com/2716069/79747091-632d1800-830b-11ea-8a87-54c0e7f2155d.png)

**Comment by jfmengels** [comment]
Thanks a lot @jhrcek :)

**Comment by jfmengels** [comment]
From what I could see, this is an issue in `stil4m/elm-syntax`. It's not the first time I have seen incorrect ranges, and I need to take some time to file issues :/

**Comment by jfmengels** [comment]
I managed to find a way around this in this package, and it has been released in v2.0.3.

I would still love for `elm-syntax` to fix this problem obviously, but this problem is at least out of the way now.

**Comment by jhrcek** [comment]
Thank you :smiley: I appreciate that you've invested time into fixing this despite it being upstream issue :heart:

**Comment by jfmengels** [comment]
I found a way to fix it that was relatively easy to implement, so why not :man_shrugging: 

Also, I started hitting it too and started to get annoyed by it :stuck_out_tongue:
