### ISSUE TITLE
NoUnused.Exports.rule - false positive when multiple modules have the same alias

### ISSUE THREAD

**Issue by jhrcek** [jfmengels/review-unused#14]
Hello @jfmengels 
This is the probably the last edge case our codebase contains :smile:

We have a weird convention for "locally extending" existing libraries.
So e.g. if there's a function `extraFunctionMissingInOriginalJsonDecode` that we're missing in  `elm/json` `Json.Decode`, we create a module named `OurCompany.Json.Decode` and then import it in other modules like so

``` elm
import Json.Decode as Decode
import OutCompany.Json.Decode as Decode

f = 
     ... Decode.extraFunctionMissingInOriginalJsonDecode ...
```

The problem is that elm-review then reports that `extraFunctionMissingInOriginalJsonDecode` is unused export in `OurCoumpany.Json.Decode` although it's actually used.

I created an SSCCE for this kind of situation here: https://github.com/jhrcek/elm-review-sscce/tree/NoUnusedExports_AliasedModules_FalsePositive

The problem in the reproducer is that A.a is considered unused even though it's actually used.
```
-- ELM-REVIEW ERROR -------------------------------------------------- src/A.elm

NoUnused.Exports: Exposed function or value `a` is never used outside this
module.

1| module A exposing (a)
                      ^


This exposed element is never used. You may want to remove it to keep your
project clean, and maybe detect some unused code in your project.
```

EDIT: I simplified the reproducer as much as possible.

**Comment by jfmengels** [comment]
Hey!

Don't worry, keep them coming, I want this package to be usable by everyone, so bug reports are welcome :wink: 

I have seen this pattern elsewhere too, [`elm-community/dict-extra`](https://package.elm-lang.org/packages/elm-community/dict-extra/latest/) even advises to do it. I personally don't like this pattern because I think this makes some information harder to get (which package did this function really come from?). But that's not the point here :smile: 

I can reproduce the error just fine with your SSCCE, so I'll try to find a fix for that when I have time. Thanks for the quality SSCCEs by the way!

Also, FYI, the problems for this issue (and the shadowing from #12) actually come from https://github.com/jfmengels/elm-review-scope, so I'm fixing it there. Since it's a tool that other packages will use, fixing these issues will improve the quality of a lot of other rules :rocket:

**Comment by jfmengels** [comment]
I think I have fixed the issue. I'd like to batch the release with an other (unrelated) improvement to `NoUnused.CustomTypeConstructors` though.

In the meantime, could you try running it in your project? To do that:
- Copy https://github.com/jfmengels/review-unused/blob/master/src/Scope.elm to `review/src/Scope.elm`
- Copy https://github.com/jfmengels/review-unused/blob/master/src/NoUnused/Exports.elm to `review/src/NoUnused/Exports2.elm` and rename the module name to `NoUnused.Exports2`
- In your review config, replace `NoUnused.Exports` by `NoUnused.Exports2`

Let me know if that solved this problem :)

**Comment by Janiczek** [comment]
@jfmengels @jhrcek 
I've tried this fixed `NoUnused.Exports2` rule in the project @jhrcek has originally tried this on (we're working for the same company :slightly_smiling_face: ) and can confirm these false positives no longer show up.

**Comment by jfmengels** [comment]
Great! I'll publish this soon-ish then. Keep the bug reports coming!

> we're working for the same company :slightly_smiling_face: 

You have a lot of familiar faces at your company. A lot of contributors to the Elm ecosystem :blush: (well, only a few, but that's still quite a lot for the size of our community!)

**Comment by kraklin** [comment]
Well, we all love to give something back to community ;) ( I work there as well :D )

**Comment by jfmengels** [comment]
Yeah, I recognized you and @Janiczek. I don't recognize anyone else (sorry if I should have :sweat_smile: )

**Comment by kraklin** [comment]
Now you do know @jhrcek :D Also, being here already - just want to thank you, `elm-review` is really useful ;) Keep up great work on it

**Comment by jfmengels** [comment]
I ended up publishing v2.0.2 with the fix. The other improvements will have to wait for a future release.

Thanks again for the help all :)

**Comment by jhrcek** [comment]
Thank you for the quick turnaround :heart_eyes:
