### ISSUE TITLE
[CustomTypeConstructor] False positive in fairly confusing situation

### ISSUE THREAD

**Issue by zwilias** [jfmengels/review-unused#15]
I made the reproduction a failing test-case, ready to be plugged in to `CustomTypeConstructorTest.elm`:

```elm
test "should not report type constructors in confusing situations" <|
            \() ->
                [ """module A exposing (A(..))

type A = Foo | Bar
"""
                , """module B exposing (B(..))

type B = A | B
"""
                , """module C exposing (foo)

import A exposing (A(..))
import B exposing (B(..))

foo = [ (Foo, A), (Bar, B) ]
"""
                ]
                    |> Review.Test.runOnModulesWithProjectData project (rule [])
                    |> Review.Test.expectNoErrors
```

I would _think_ that it would see the type constructor `A` from module `B` being used, but it seems to get confused and blame this on the `type A` from module `A`?

```
↓ NoUnused.CustomTypeConstructorsTest
↓ NoUnusedCustomTypeConstructors
↓ Using constructors from others modules (package project)
✗ should not report type constructors in confusing situations

    DID NOT EXPECT ERRORS

    I expected no errors for module `B` but found:

      - `Type constructor `A` is not used.`
        at { start = { row = 3, column = 10 }, end = { row = 3, column = 11 } }
```

**Comment by jfmengels** [comment]
Fixed in v2.0.3, thanks for the report :blush: 
Th fix has been made in https://github.com/jfmengels/elm-review-scope.

The problem was something I was expecting for a while to pop-up, but was "low" on my radar because I hadn't run into it. `elm-review-scope` provides a way to let you query the module name of a value/type (`realModuleName`), but it didn't make any difference between types and values. So yes, it was confused.

I resolved this by making a breaking change, and `realModuleName` has been split into `moduleNameForValue` and `moduleNameForType`, which shouldn't be confused now (:crossed_fingers:).
