### ISSUE TITLE
[Exports] False positive with 'shadowed' module

### ISSUE THREAD

**Issue by zwilias** [jfmengels/review-unused#16]
Similar to #14, with one important difference: one module is aliased to the same name as another module.

This comes up, for example, when having something like `import Html.Extra as Html`, so we can use `Html.none` without the `Extra` prefix.

> in that specific case, it doesn't actually happen as `Html` comes from a dependency, but the idea is the same!

As a failing testcase:

```elm
test "should not report a function in a 'shadowed' module" <|
            \() ->
                [ """module Foo exposing (foo)

foo = 1
""", """module Bar exposing (bar)

bar = 2
""", """module Main exposing (main)

import Bar as Foo
import Foo

main = [ Foo.foo, Foo.bar ]
""" ]
                    |> Review.Test.runOnModulesWithProjectData application rule
                    |> Review.Test.expectNoErrors
```

Which fails with

```
↓ NoUnused.ExportsTest
↓ NoUnusedExports
↓ Functions and values
✗ should not report a function in a 'shadowed' module

    DID NOT EXPECT ERRORS

    I expected no errors for module `Foo` but found:

      - `Exposed function or value `foo` is never used outside this module.`
        at { start = { row = 1, column = 22 }, end = { row = 1, column = 25 } }
```

**Comment by jfmengels** [comment]
Fixed in v2.0.3, thanks for the report :blush: 
Th fix has been made in https://github.com/jfmengels/elm-review-scope.

FYI, the problem was indeed that when the qualified name only has a single segment (like `Foo.a`, not `Foo.Bar.a`), then I looked at aliases if there were any. Since in this case, there is one, even when I can't find the function I'm looking for, I take a random one from the aliases.

The trouble was that I was not looking at the non-aliased modules with the same name. Now that's done :)
