### ISSUE TITLE
removing aliasing in imports can cause compilation errors

### ISSUE THREAD

**Issue by BrianHicks** [jfmengels/review-unused#8]
I had the following import statements:

```elm
import Html as RootHtml
import Html.Styled as Html
```

What happened:

1. I used `elm-review --fix`
2. it correctly identified `RootHtml` as unused and removed the alias
3. that left `import Html`, which caused a conflict with `import Html.Styled as Html`.

I would have expected the whole import statement to have been removed in this case.

**Comment by jfmengels** [comment]
> I would have expected the whole import statement to have been removed in this case.

Good point. When the module does not have `exposing (...)` then the whole import can be removed :+1: 

I made that happen and stop exposing a fix if the result would lead a naming conflict. [v1.0.3](https://github.com/jfmengels/review-unused/releases/tag/1.0.3) contains those.

Once again, thank you for reporting this! Keep the issues coming! (Although I hope we'll run out of problems soon :sweat_smile: )

PS: I just noticed that the rule does not handle pattern / argument aliases at all. I'll probably add that in the next release, if it turns out not to be all too complicated.
